/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DiemTTDAO;
import Model.DiemTT;
import Model.SinhVien;
import java.util.ArrayList;
import DBEnginee.DBEngine;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class QLDiemTT extends javax.swing.JFrame {
    private ArrayList<DiemTT> dsDiemTT = new ArrayList<>();
    private ArrayList<SinhVien> dsSinhVien = new ArrayList<>();
    private DiemTT diemSV = new DiemTT();
    private String fileDiem = "diem.txt";
    private String fileSV ="sinhvien.txt";
    private DBEngine dBEngine = new DBEngine();
    private String maSV = "";
    private int dongClick= -1;
    /**
     * Creates new form QLDiemTT
     */
    public QLDiemTT() {
        initComponents();
        loadFileDiem();
        loadFileSV();
        loadComBoxSV();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDiem = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxSV = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Quản Lý Điểm Thực Tập ");

        jTableDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDiem);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sắp Xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        btnXoaTrang.setText("Xóa Trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        jLabel2.setText("Sinh Viên");

        jComboBoxSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSVActionPerformed(evt);
            }
        });

        jLabel3.setText("Điểm");

        jLabel4.setText("Tìm kiếm theo mã sinh viên");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaTrang)
                            .addComponent(btnTimKiem))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSapXep)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuayLai)
                    .addComponent(btnXoaTrang))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        MenuQuanLyTT menuQuanLyTT = new MenuQuanLyTT();
        menuQuanLyTT.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed
    private String xepLoai(){
        String diem = txtDiem.getText().toString().trim();
        double diemTT = Double.parseDouble(diem);
        if(diemTT<5){
            return "Yếu";
        }else if(diemTT<=6.9){
            return "Trung bình";
        }else if(diemTT<=8.4){
            return "Khá";
        }else{
            return "Giỏi";
        }
    }
    boolean kiemtra(String kt){
       boolean x=true;
       for (var it:dsDiemTT){
           if(it.getMaSV().trim().equals(kt.trim()))
               x=false;
       } 
       return  x;
    }
     
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String diem = txtDiem.getText().toString().trim();
        if(diem.isEmpty()){
           JOptionPane.showMessageDialog(this,"Điểm không được để trống !");
        }else{
            double diemTT = Double.parseDouble(diem);
           if(diemTT<0){
           JOptionPane.showMessageDialog(this,"Điểm không hợp lệ !");
          }else{
               if(kiemtra(maSV)){
                   diemSV = new DiemTT(maSV,diem,xepLoai());
                   dsDiemTT.add(diemSV);
                   luuFileDiem();
                   loadTable();
               }else{
             JOptionPane.showMessageDialog(this,"Sinh viên đã được thêm điểm !");   
               }         
            }
        }     
    }//GEN-LAST:event_btnThemActionPerformed
    
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        dongClick = jTableDiem.getSelectedRow();
        String diem = txtDiem.getText().toString().trim();
        if (dongClick != -1) {
            if (diem.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Điểm không được để trống !");
            } else {
                double diemTT = Double.parseDouble(diem);
                if (diemTT < 0) {
                    JOptionPane.showMessageDialog(this, "Điểm không hợp lệ !");
                } else {
                    if (kiemtra(maSV)==false) {
                        if(maSV.equals(dsDiemTT.get(dongClick).getMaSV().trim())){
                            diemSV = new DiemTT(maSV, diem, xepLoai());
                            dsDiemTT.set(dongClick,diemSV);
                            luuFileDiem();
                            loadTable();
                        }else {
                            JOptionPane.showMessageDialog(this, "Sinh viên đã được thêm điểm !");
                        }                       
                    }else{
                            diemSV = new DiemTT(maSV, diem, xepLoai());
                            dsDiemTT.set(dongClick,diemSV);
                            luuFileDiem();
                            loadTable();
                    }
                }
           }
      }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        dongClick = jTableDiem.getSelectedRow();      
        if(dongClick != -1){
            int check = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không ?"
                    ,"Dialog Confirm",JOptionPane.YES_NO_OPTION);
            if(check==JOptionPane.YES_OPTION){
                dsDiemTT.remove(dongClick);
                luuFileDiem();
                loadTable();
            }          
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        Collections.sort(dsDiemTT,new Comparator<DiemTT>(){
            @Override
            public int compare(DiemTT o1, DiemTT o2) {   
                int d1 = Integer.parseInt(o1.getDiem());
                int d2 = Integer.parseInt(o2.getDiem());
              return d1 > d2 ? 1:-1;
            }
        });
       loadTable();
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maSVSearch = txtTimKiem.getText().toString().trim().toUpperCase();
        ArrayList<DiemTT> dsDiemSearch = new ArrayList<>();
        for(var ds : dsDiemTT){
            if(ds.getMaSV().trim().toUpperCase().contains(maSVSearch)){
                dsDiemSearch.add(ds);
            }
        }
        jTableDiem.setModel(new DiemTTDAO(dsDiemSearch,dsSinhVien));
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        txtDiem.setText("");
        txtTimKiem.setText("");
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void jComboBoxSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSVActionPerformed
        String tenSV = (String) jComboBoxSV.getSelectedItem();
        for(var sv : dsSinhVien){
            if(sv.getHoTen().equals(tenSV)){
                maSV = sv.getMaSinhVien();
           
            }
        }
    }//GEN-LAST:event_jComboBoxSVActionPerformed

    private void jTableDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDiemMouseClicked
        dongClick = jTableDiem.getSelectedRow();
        if(dongClick !=-1){
            diemSV = dsDiemTT.get(dongClick);
            
            txtDiem.setText(diemSV.getDiem()+"");
            jComboBoxSV.setSelectedItem(diemSV.getMaSV());
             
        }
    }//GEN-LAST:event_jTableDiemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDiemTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDiemTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDiemTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDiemTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDiemTT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JComboBox<String> jComboBoxSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDiem;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadFileDiem() {
        try {
           dsDiemTT=(ArrayList<DiemTT>) dBEngine.docFile(fileDiem);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,e);
        }
    }

    private void loadFileSV() {
        try {
           dsSinhVien=(ArrayList<SinhVien>) dBEngine.docFile(fileSV);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,e);
        }
    }
    private void luuFileDiem(){
        try {
            dBEngine.LuuFile(fileDiem,dsDiemTT);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
    }
    
    private void loadComBoxSV() {
        jComboBoxSV.removeAllItems();
        for (var sv : dsSinhVien) {
            jComboBoxSV.addItem(sv.getHoTen());
        }
    }

    private void loadTable() {
        jTableDiem.setModel(new DiemTTDAO(dsDiemTT,dsSinhVien));
    }

   
}
