/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.XemLichTTDAO;
import Model.DangKyTT;
import Model.DeTai;
import Model.GiangVien;
import java.util.ArrayList;
import DBEnginee.DBEngine;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class XemLichTT extends javax.swing.JFrame {
    private String maSV;
    private ArrayList<DeTai> dsDT = new ArrayList<DeTai>();
    private ArrayList<GiangVien> dsGV = new ArrayList<GiangVien>();
    private ArrayList<DangKyTT> dsDK = new ArrayList<DangKyTT>();
    private ArrayList<DangKyTT> dsDKAll = new ArrayList<DangKyTT>();
    private String fileDT = "detai.txt";
    private String fileDK = "dangkytt.txt";
    private String fileGV = "giangvien.txt";
    private int dongClik = -1;
    private DBEngine dBEngine = new DBEngine();
    /**
     * Creates new form XemLichTT
     */
    public XemLichTT(String maSV) {
        this.maSV = maSV;
        initComponents();
        loadFileDT();
        loadFileGV();
        loafFileDK();
        loadTable();
    }

    private XemLichTT() {
        loadFileDT();
        loadFileGV();
        loafFileDK();
        loadTable();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableXemLichTT = new javax.swing.JTable();
        btnDenDKy = new javax.swing.JButton();
        btnHuyDky = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Xem Lịch Thực Tập");

        jTableXemLichTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableXemLichTT);

        btnDenDKy.setText("Đến đăng ký thực tập");
        btnDenDKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenDKyActionPerformed(evt);
            }
        });

        btnHuyDky.setText("Hủy đăng ký");
        btnHuyDky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDkyActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnHuyDky, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDenDKy, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDenDKy)
                    .addComponent(btnHuyDky))
                .addGap(47, 47, 47)
                .addComponent(btnQuayLai)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyDkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDkyActionPerformed
       dongClik = jTableXemLichTT.getSelectedRow();
       if(dongClik != -1){
          int check = JOptionPane.showConfirmDialog(null,"Bạn chắc chắn muốn hủy không ?" 
                  ,"Dialog Confirm",JOptionPane.YES_NO_OPTION);
           if(check == JOptionPane.YES_OPTION){
                dsDK.remove(dsDKAll.get(dongClik));
                luuFile();
                loafFileDK();
                loadTable();
           }          
       }
    }//GEN-LAST:event_btnHuyDkyActionPerformed

    private void btnDenDKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenDKyActionPerformed
        DangKyThucTap dangKyThucTap = new DangKyThucTap();
        dangKyThucTap.setMaSV(maSV);
        dangKyThucTap.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDenDKyActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        MenuSinhVienTT menuSinhVienTT = new MenuSinhVienTT();
        menuSinhVienTT.setMaSV(maSV);
        menuSinhVienTT.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemLichTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemLichTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemLichTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemLichTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemLichTT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDenDKy;
    private javax.swing.JButton btnHuyDky;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableXemLichTT;
    // End of variables declaration//GEN-END:variables

     private void loadFileDT() {
        try {
           dsDT=(ArrayList<DeTai>) dBEngine.docFile(fileDT);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,e);
        }
    }

    private void loadFileGV() {
        try {
           dsGV =(ArrayList<GiangVien>) dBEngine.docFile(fileGV);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,e);
        }
    }   
    private void loafFileDK() {
        try {
            dsDKAll = (ArrayList<DangKyTT>) dBEngine.docFile(fileDK);
            ArrayList<DangKyTT> dsKyTTs = new ArrayList<>();
            for(var list : dsDKAll){
                if(list.getMaSV()!=null && list.getMaSV().equals(maSV)){
                    dsKyTTs.add(list);
                }
                 System.out.println(list.getMaSV()+" "+list.getMaDT());
            }
            dsDK = dsKyTTs;
        } catch (Exception e) {
            e.printStackTrace();
        }
      
    }
    private void luuFile(){
        try {
            dBEngine.LuuFile(fileDK,dsDK);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void loadTable() {
        jTableXemLichTT.setModel(new XemLichTTDAO(dsDT,dsDK,dsGV));
     
    }

    
}
